### ISSUE TITLE
Error startup

### ISSUE THREAD

**Issue by xhendrikg** [VendoAU/MapTooltip#1]
I get this error when i try to startup minecraft with the mod in multimc: 
![grafik](https://user-images.githubusercontent.com/69456711/126541703-4ddf8d45-5977-490c-bb17-5527c0bf6dbe.png)
i use fabric and 1.17.1. 

The map tooltip version is 1.3.0

**Comment by VendoAU** [comment]
Make sure you are using [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)

**Comment by VendoAU** [comment]
Closing this as 1.17 and up no longer require fabric api
