### ISSUE TITLE
Creates Errors and Kills Voice Chat Mod With it

### ISSUE THREAD

**Issue by RustinPlays** [VendoAU/MapTooltip#11]
When loading into a server, the Mod creates some error and takes down Voice chat with it, it stops VC from connecting to the server.

Issue was found by owner of Simple Voice Chat due to my client issue

**Comment by VendoAU** [comment]
Please send logs

**Comment by VendoAU** [comment]
I've sent you a message on discord to get some more details

**Comment by VendoAU** [comment]
The cached map file was corrupted, this has been fixed in 8bdb987
