### ISSUE TITLE
Bug: Item tooltip is not dynamically adjust the position of the image of the map

### ISSUE THREAD

**Issue by EGOIST1372** [VendoAU/MapTooltip#4]
Item tooltip is not dynamically adjust the position of the image of the map
map should be shown on top of the tooltip in this screenshot (if the item was in my hotbar the image completely going out of the display)
![2022-04-17_18 12 56](https://user-images.githubusercontent.com/86555131/163718735-a80ed90e-e05a-413f-988c-38ba0154f4d6.png)

**Comment by VendoAU** [comment]
This should be fixed in version 2.0.0 as the image is now actually part of the tooltip.
