### ISSUE TITLE
[Feature Request] Cache map from servers

### ISSUE THREAD

**Issue by lerokko** [VendoAU/MapTooltip#8]
Currently I have to put each map in my inventory to see what it contains. I am making map art and would love to see a feature where the last known version of a map i cached locally and the game just uses that cached image for the tool tip for maps in containers. Maybe have a disclaimer in the tooltip.

I am not sure if that is technically possible since I do not see the map id in the tooltip but I can see that its has an NBT tag before moving it in my inventory.

I would greatly help me not having to put 40+ maps in my inventory every time I re-log since they are sorted in the chest.

**Comment by VendoAU** [comment]
I'll add this as a feature when I update to 1.21
